/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseForm: typeof import('./src/components/form/BaseForm.vue')['default']
    BaseFormField: typeof import('./src/components/form/BaseFormField.vue')['default']
    BaseFormFile: typeof import('./src/components/form/BaseFormFile.vue')['default']
    BaseFormInput: typeof import('./src/components/form/BaseFormInput.vue')['default']
    BaseFormPickerSelect: typeof import('./src/components/form/BaseFormPickerSelect.vue')['default']
    BaseFormSelect: typeof import('./src/components/form/BaseFormSelect.vue')['default']
    BaseFormSubmitButton: typeof import('./src/components/form/BaseFormSubmitButton.vue')['default']
    BaseFormSubmitPanel: typeof import('./src/components/form/BaseFormSubmitPanel.vue')['default']
    BaseHeader: typeof import('./src/components/BaseHeader.vue')['default']
    BaseLoadingSpinner: typeof import('./src/components/BaseLoadingSpinner.vue')['default']
    BaseModal: typeof import('./src/components/modal/BaseModal.vue')['default']
    BaseTable: typeof import('./src/components/table/BaseTable.vue')['default']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BCardTitle: typeof import('bootstrap-vue-next/components/BCard')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next/components/BNav')['BNavItemDropdown']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    ContentButton: typeof import('./src/components/content/ContentButton.vue')['default']
    ContentDivider: typeof import('./src/components/content/ContentDivider.vue')['default']
    ContentImage: typeof import('./src/components/content/ContentImage.vue')['default']
    ContentList: typeof import('./src/components/content/ContentList.vue')['default']
    ContentParagraph: typeof import('./src/components/content/ContentParagraph.vue')['default']
    ContentQuote: typeof import('./src/components/content/ContentQuote.vue')['default']
    ContentSubtitle: typeof import('./src/components/content/ContentSubtitle.vue')['default']
    ContentTitle: typeof import('./src/components/content/ContentTitle.vue')['default']
    ContentVideo: typeof import('./src/components/content/ContentVideo.vue')['default']
    IBiArrowLeft: typeof import('~icons/bi/arrow-left')['default']
    IBiArrowRight: typeof import('~icons/bi/arrow-right')['default']
    IClarityAvatarLine: typeof import('~icons/clarity/avatar-line')['default']
    IMaterialSymbolsAdd: typeof import('~icons/material-symbols/add')['default']
    IMaterialSymbolsArrowDownward: typeof import('~icons/material-symbols/arrow-downward')['default']
    IMaterialSymbolsArrowUpward: typeof import('~icons/material-symbols/arrow-upward')['default']
    IMaterialSymbolsArticlePerson: typeof import('~icons/material-symbols/article-person')['default']
    IMaterialSymbolsDelete: typeof import('~icons/material-symbols/delete')['default']
    IMaterialSymbolsPersonAdd: typeof import('~icons/material-symbols/person-add')['default']
    IMaterialSymbolsPersonRemove: typeof import('~icons/material-symbols/person-remove')['default']
    IMaterialSymbolsPlayArrowRounded: typeof import('~icons/material-symbols/play-arrow-rounded')['default']
    IMaterialSymbolsSettingsRounded: typeof import('~icons/material-symbols/settings-rounded')['default']
    NavbarWallet: typeof import('./src/components/wallet/NavbarWallet.vue')['default']
    ProjectContent: typeof import('./src/components/content/ProjectContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectWallettButton: typeof import('./src/components/wallet/SelectWallettButton.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next/directives/BColorMode')['vBColorMode']
    vBToggle: typeof import('bootstrap-vue-next/directives/BToggle')['vBToggle']
  }
}
