@PCONTB.Panel.Server_HostAddress = http://localhost:5020

POST {{PCONTB.Panel.Server_HostAddress}}/account/auth/register
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "username": "test",
    "email": "test@example.com",
    "password": "Test1234!"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/account/auth/login
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "login": "test",
    "password": "Test1234!"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/account/auth/login
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "login": "test2",
    "password": "Test1234!"
}


###
POST {{PCONTB.Panel.Server_HostAddress}}/account/users/add
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "username": "test2",
    "email": "test2@example.com",
    "password": "Test1234!",
    "role": 1
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/account/auth/logout
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/account/auth/get-session
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/account/users/update
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
  "id": "1856d2d1-1cd7-48b6-8130-ac7cb02354f8",
  "username": "test2",
  "email": "test2@example.com"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/account/users/get-all
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{

}

###
POST {{PCONTB.Panel.Server_HostAddress}}/account/users/update-role/form
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
  "id": "ad8c3930-f4c9-4505-8971-134c193fb461"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/account/users/update-role
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
  "id": "df49a7b3-05b5-474e-915e-55cb9317277f",
  "role": 1
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/account/users/update/form
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
  "id": "ad8c3930-f4c9-4505-8971-134c193fb461"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/projects/projects/get-all
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/projects/projects/get-by-id
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
  "id": "8b4d94df-f628-45bf-8904-25cf1489feec"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/projects/projects/add/form
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/projects/projects/add
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "categoryId": "7bc31256-4f02-414e-8c1c-ba0a3c601dcf",
    "countryId": "569b9920-4a38-4aed-ba27-5ae3a55207b7",
    "name": "Test2"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/projects/projects/add/validate
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "name": null,
    "userId": "2751e0ec-284f-4ba9-a5b6-81f0e0b9170b"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/projects/projects/add
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "name": ""
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/projects/projects/update/form
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "id": "0c360b8f-35fd-440c-8254-006a09c0b8bd"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/project/update/validate
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "id": "0c360b8f-35fd-440c-8254-006a09c0b8bd",
    "name": null,
    "userId": "2751e0ec-284f-4ba9-a5b6-81f0e0b9170b"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/projects/projects/update
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "id": "0c360b8f-35fd-440c-8254-006a09c0b8bd",
    "name": "",
    "userId": "2751e0ec-284f-4ba9-a5b6-81f0e0b9170b"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/project/delete/validate
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "id": "0c360b8f-35fd-440c-8254-006a09c0b8bd"
    "name": "test2",
    "userId": "2751e0ec-284f-4ba9-a5b6-81f0e0b9170b"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/project/delete
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "id": "6023a8b5-4a2c-41a1-8229-eecd723f346e"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/locations/countries/get-by-id
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "id": "06202cd8-c7e1-49b3-9f27-3ca4ddbef153"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/locations/countries/get-all
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/locations/countries/add/form
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/locations/countries/add
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "name": "Poland"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/locations/countries/update/form
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "id": "06202cd8-c7e1-49b3-9f27-3ca4ddbef153"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/locations/countries/update
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "id": "06202cd8-c7e1-49b3-9f27-3ca4ddbef153",
    "name": "Poland"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/locations/countries/delete
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "id": "06202cd8-c7e1-49b3-9f27-3ca4ddbef153"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/projects/categories/add/form
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{

}

###
POST {{PCONTB.Panel.Server_HostAddress}}/projects/categories/add
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "name": "IT",
    "subcategories": [
        {
          "name": "Frontend"
        },
        {
          "name": "Backend"
        },
        {
          "name": "DevOps"
        }
    ]
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/projects/categories/update/form
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "id": "6784f868-ad74-4c8e-9263-58883975288b"
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/projects/categories/update
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "id": "6784f868-ad74-4c8e-9263-58883975288b",
    "name": "IT",
    "subcategories": [
        {
          "id": "49e259f0-e6d2-45e7-abd5-d7d466758944",
          "name": "Backend",
          "categoryId": "6784f868-ad74-4c8e-9263-58883975288b"
        },
        {
          "id": "7819ca96-c80a-4a61-bb7d-7b515a32906c",
          "name": "Frontend",
          "categoryId": "6784f868-ad74-4c8e-9263-58883975288b"
        },
        {
          "id": "2e29e664-06b9-4d4c-a17d-238d79f27761",
          "name": "Dev Ops",
          "categoryId": "6784f868-ad74-4c8e-9263-58883975288b"
        }
    ]
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/projects/categories/get-all
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
}

###
POST {{PCONTB.Panel.Server_HostAddress}}/projects/categories/delete
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
    "id": "80f03eac-03b8-462a-9d48-7b8266f49238"
}